-- Migration: 004_seed_careers.sql
-- Description: Insert initial career profiles

INSERT INTO careers (
  title,
  slug,
  primary_archetype,
  secondary_archetype,
  defensibility_score,
  factor_physical_presence,
  factor_human_judgment,
  factor_creative_originality,
  factor_relationship_dependency,
  factor_regulatory_barrier,
  entry_salary_low,
  entry_salary_high,
  mid_salary_low,
  mid_salary_high,
  senior_salary_low,
  senior_salary_high,
  day_to_day_description,
  ai_impact_analysis,
  skills_to_develop,
  education_path,
  real_world_examples,
  status,
  created_at,
  updated_at
) VALUES

-- BUILDER ARCHETYPE
(
  'Commercial Electrician',
  'commercial-electrician',
  'Builder',
  NULL,
  88,
  95,
  85,
  60,
  75,
  95,
  32000,
  42000,
  52000,
  68000,
  75000,
  95000,
  'You install, maintain, and repair electrical systems in office buildings, factories, and malls. Your days involve reading blueprints, running wire, troubleshooting broken circuits, and making sure everything is up to code. Safety is huge—one mistake could be really dangerous.',
  'AI can model electrical systems and predict maintenance needs, but the physical installation, hands-on problem-solving, and safety judgment still require experienced humans. Electricians will increasingly use diagnostic tools powered by AI to work faster.',
  '[{"skill": "Blueprint Reading & Electrical Code", "priority": "high", "how_to_develop": "Take trade school courses focused on electrical codes (NEC) and blueprint interpretation. Study 40-60 hours per week for 2-3 years in an apprenticeship."}, {"skill": "Troubleshooting & Problem-Solving", "priority": "high", "how_to_develop": "Learn through hands-on apprenticeships under experienced electricians. Work on real equipment failures to develop diagnostic intuition."}, {"skill": "Safety Management", "priority": "high", "how_to_develop": "Complete OSHA training, CPR certification, and site safety courses. Practice hazard identification on every job."}]',
  '{"type": "apprenticeship", "details": "Complete a 4-5 year electrician apprenticeship through a union or trade organization. Combine 2000 hours of on-the-job training with classroom instruction.", "duration": "4-5 years"}',
  '[{"name": "Mike Rowe", "role": "Master Electrician & TV Host", "achievement": "Documented the importance of skilled trades to American infrastructure and inspired thousands to pursue electrical careers."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Civil Engineer',
  'civil-engineer',
  'Builder',
  'Strategist',
  76,
  70,
  80,
  75,
  70,
  85,
  52000,
  65000,
  70000,
  90000,
  95000,
  130000,
  'You design and oversee construction projects like bridges, roads, buildings, and water systems. You work with architects, contractors, and government agencies to make sure projects are safe, environmentally sound, and built on time. You spend time at computers designing and at job sites checking progress.',
  'AI tools are revolutionizing design optimization and cost prediction, but civil engineers still need to understand structural principles, navigate regulations, and make judgment calls about public safety. Human expertise in project management and stakeholder coordination remains essential.',
  '[{"skill": "CAD & Design Software", "priority": "high", "how_to_develop": "Learn AutoCAD, Civil 3D, and structural analysis software through university courses and hands-on projects. Complete 100+ hours of software practice."}, {"skill": "Project Management & Leadership", "priority": "high", "how_to_develop": "Pursue a Project Management Professional (PMP) certification. Lead small teams on projects and learn scheduling, budgeting, and risk management."}, {"skill": "Regulatory & Environmental Knowledge", "priority": "medium", "how_to_develop": "Study environmental regulations, zoning laws, and building codes specific to your region. Take courses in sustainable design and environmental engineering."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in Civil Engineering (ABET accredited). Pursue Professional Engineer (PE) licensure by passing the Fundamentals of Engineering (FE) exam and gaining 4 years of work experience.", "duration": "4 years + apprenticeship"}',
  '[{"name": "Gustave Eiffel", "role": "Structural Engineer", "achievement": "Designed the Eiffel Tower and pioneered the use of iron in large-scale construction, revolutionizing civil engineering."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Robotics Technician',
  'robotics-technician',
  'Builder',
  'Creator',
  82,
  85,
  80,
  85,
  60,
  75,
  38000,
  50000,
  55000,
  75000,
  80000,
  110000,
  'You build, test, and repair robots used in manufacturing, research, and medical settings. You work with mechanical parts, electronics, and programming to make robots do what they''re designed for. Problem-solving is constant—when a robot breaks or doesn''t work right, you figure out why and fix it.',
  'AI is enhancing robot capabilities and autonomous function, but technicians are needed to physically maintain equipment, diagnose hardware issues, and customize robots for specific tasks. The role is expanding as robots become more prevalent.',
  '[{"skill": "Mechanical & Electrical Assembly", "priority": "high", "how_to_develop": "Take robotics courses in trade schools or vocational programs. Build robots from kits and learn through hands-on assembly and troubleshooting."}, {"skill": "Programming & Control Systems", "priority": "high", "how_to_develop": "Learn Python, C++, and ROS (Robot Operating System). Take courses on microcontroller programming and PLC systems."}, {"skill": "Mechanical Problem-Solving", "priority": "medium", "how_to_develop": "Work on real robots, study failures, and experiment with modifications. Learn through apprenticeships in robotics companies."}]',
  '{"type": "trade", "details": "Complete a robotics technician certification program at a community college or trade school (2 years). Combine classroom learning with hands-on lab work and internships at robotics companies.", "duration": "2-3 years"}',
  '[{"name": "Rodney Brooks", "role": "Roboticist & Entrepreneur", "achievement": "Founded iRobot and created the Roomba, revolutionizing consumer robotics and demonstrating the importance of practical engineering expertise."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Custom Furniture Maker',
  'custom-furniture-maker',
  'Builder',
  'Creator',
  85,
  95,
  80,
  90,
  75,
  40,
  28000,
  40000,
  50000,
  70000,
  75000,
  120000,
  'You design and build one-of-a-kind or semi-custom furniture for clients. Every day involves sketching ideas, measuring spaces, selecting materials, and crafting pieces at your workshop. You work with wood, metal, or other materials, using both hand tools and machinery. Client relationships are key since you''re building something personal for them.',
  'AI can optimize designs and material usage, but the creative vision, craftsmanship, and hands-on building remain uniquely human skills. Custom work thrives on personal relationships and creative problem-solving that can''t be automated.',
  '[{"skill": "Furniture Design & Spatial Planning", "priority": "high", "how_to_develop": "Study design principles, learn CAD software, and practice sketching. Take courses in furniture design at art schools or design institutes."}, {"skill": "Woodworking & Craftsmanship", "priority": "high", "how_to_develop": "Learn through apprenticeships with master craftspeople. Build projects and develop expertise in joinery, finishing, and material selection."}, {"skill": "Client Communication & Project Management", "priority": "medium", "how_to_develop": "Work directly with clients, learn to understand their vision, and manage timelines. Build a portfolio and gather testimonials."}]',
  '{"type": "apprenticeship", "details": "Apprentice under a master furniture maker for 3-4 years while learning design and technical skills. Many also earn degrees in furniture design or fine arts.", "duration": "3-4 years"}',
  '[{"name": "George Nakashima", "role": "Master Furniture Craftsman", "achievement": "Created iconic handcrafted furniture using natural wood, proving the enduring value of bespoke craftsmanship in a mass-produced world."}]',
  'active',
  NOW(),
  NOW()
),

-- HEALER ARCHETYPE
(
  'Emergency Room Nurse',
  'emergency-room-nurse',
  'Healer',
  'Guardian',
  92,
  100,
  95,
  70,
  90,
  95,
  48000,
  60000,
  65000,
  85000,
  85000,
  110000,
  'You work in fast-paced emergency departments helping people in crisis. You assess patients, administer medications, monitor vital signs, and support doctors during emergencies. One moment you''re helping someone with a broken arm, the next you''re responding to a life-threatening situation. You need to stay calm under pressure and make quick decisions.',
  'AI can help with triage recommendations and vital sign monitoring, but nurses provide irreplaceable empathy, complex clinical judgment, and physical care that critical patients desperately need. The human element is absolutely central to emergency care.',
  '[{"skill": "Clinical Assessment & Critical Thinking", "priority": "high", "how_to_develop": "Complete your RN program with strong clinical rotations. Practice assessing patients under supervision and build pattern recognition skills."}, {"skill": "Emergency Protocols & Advanced Life Support", "priority": "high", "how_to_develop": "Complete ACLS (Advanced Cardiac Life Support) and BLS (Basic Life Support) certifications. Specialize in emergency nursing through certifications like CEN (Certified Emergency Nurse)."}, {"skill": "Communication Under Stress", "priority": "high", "how_to_develop": "Practice de-escalation techniques, work with difficult patients, and develop emotional intelligence. Participate in team training and simulations."}]',
  '{"type": "degree", "details": "Earn a Bachelor of Science in Nursing (BSN) from an accredited program. Pass the NCLEX-RN licensing exam. Complete additional certifications in emergency nursing.", "duration": "4 years + licensing"}',
  '[{"name": "Florence Nightingale", "role": "Pioneering Nurse", "achievement": "Revolutionized nursing during the Crimean War, proving that skilled nursing care and data-driven decisions could save lives and transform healthcare."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Physical Therapist',
  'physical-therapist',
  'Healer',
  NULL,
  87,
  95,
  90,
  75,
  85,
  90,
  55000,
  68000,
  75000,
  95000,
  100000,
  135000,
  'You help people recover from injuries and improve their movement and function. You work with patients recovering from surgery, athletes with injuries, or people with chronic conditions. Each session involves exercises, hands-on treatment, and lots of encouragement. You tailor every plan to the individual.',
  'AI can optimize exercise plans and track progress, but physical therapy requires human touch, assessment of pain and movement, and the motivational relationship that drives patient recovery. The hands-on skilled work is difficult to automate.',
  '[{"skill": "Anatomy, Physiology & Movement Science", "priority": "high", "how_to_develop": "Master these subjects through your doctorate program. Study human movement patterns, biomechanics, and rehabilitation principles."}, {"skill": "Manual Therapy & Treatment Techniques", "priority": "high", "how_to_develop": "Complete specialized certifications in manual therapy (like AAPT or IAOM). Practice hands-on techniques under supervision."}, {"skill": "Patient Motivation & Education", "priority": "medium", "how_to_develop": "Work directly with diverse patients. Learn motivational interviewing and teach people to self-manage their recovery."}]',
  '{"type": "degree", "details": "Earn a Doctor of Physical Therapy (DPT) degree from an accredited program (3 years). Pass the NPTE licensing exam. Consider additional specializations.", "duration": "3 years post-bachelor''s + licensing"}',
  '[{"name": "Paul McCreesh", "role": "Sports Physical Therapist", "achievement": "Pioneered sports rehabilitation techniques that have helped top athletes return to peak performance after severe injuries."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Veterinarian',
  'veterinarian',
  'Healer',
  'Guardian',
  84,
  90,
  90,
  70,
  80,
  95,
  50000,
  65000,
  80000,
  110000,
  120000,
  160000,
  'You care for animals—from house pets to livestock. You diagnose diseases, perform surgeries, prescribe medications, and counsel pet owners. Some days you''re performing surgery, other days you''re comforting a sick animal or advising on nutrition and behavior. You need to love animals and be good with people too.',
  'AI can assist with diagnosis and imaging analysis, but veterinarians provide irreplaceable physical examination skills, surgical expertise, and the ability to assess animal behavior and communicate with owners. Empathy and judgment are central to the role.',
  '[{"skill": "Anatomy, Physiology & Disease Recognition", "priority": "high", "how_to_develop": "Master these through veterinary school. Study multiple species and understand disease processes and diagnostic techniques."}, {"skill": "Surgical & Medical Skills", "priority": "high", "how_to_develop": "Gain hands-on experience through veterinary internships and rotations. Practice surgical techniques and develop clinical judgment."}, {"skill": "Client Communication & Business Sense", "priority": "medium", "how_to_develop": "Work in veterinary clinics during school. Learn to explain medical concepts to pet owners and manage a practice business."}]',
  '{"type": "degree", "details": "Complete a Doctor of Veterinary Medicine (DVM) degree from an accredited veterinary school (4 years). Pass the NAVLE licensing exam. Consider internships and specializations.", "duration": "4 years + licensing"}',
  '[{"name": "James Herriot", "role": "Veterinarian & Author", "achievement": "Documented the art and science of veterinary practice in rural England, showing the profound impact of veterinary care on animals and their families."}]',
  'active',
  NOW(),
  NOW()
),
(
  'School Counselor',
  'school-counselor',
  'Healer',
  'Connector',
  79,
  70,
  90,
  75,
  90,
  75,
  35000,
  48000,
  52000,
  68000,
  70000,
  95000,
  'You support students'' emotional, social, and academic development. You listen to their problems, help them navigate friendships and family issues, and guide them toward college or career paths. You might counsel a student through anxiety, mediate peer conflicts, or advise on choosing classes. You''re part counselor, part mentor, part advocate.',
  'AI can help identify at-risk students and provide mental health resources, but students need human connection, empathy, and someone who knows them personally. The therapeutic relationship is irreplaceable and central to counseling effectiveness.',
  '[{"skill": "Counseling & Active Listening", "priority": "high", "how_to_develop": "Complete a master''s program in school counseling. Practice counseling skills in supervised settings and earn certifications."}, {"skill": "Child & Adolescent Development", "priority": "high", "how_to_develop": "Study developmental psychology and trauma-informed practices. Work with diverse student populations during your internship."}, {"skill": "College & Career Guidance", "priority": "medium", "how_to_develop": "Learn about college admissions, financial aid, and career pathways. Stay updated on labor market trends and educational opportunities."}]',
  '{"type": "degree", "details": "Earn a Master''s degree in School Counseling from an accredited program (2 years post-bachelor''s). Complete supervised internship hours and pass state licensure exams.", "duration": "2 years + internship"}',
  '[{"name": "Nel Noddings", "role": "Education Theorist & Counselor", "achievement": "Developed care-centered approaches to education, demonstrating how human relationships and empathy are foundational to student success."}]',
  'active',
  NOW(),
  NOW()
),

-- STRATEGIST ARCHETYPE
(
  'Urban Planner',
  'urban-planner',
  'Strategist',
  'Builder',
  73,
  60,
  85,
  80,
  75,
  85,
  45000,
  58000,
  65000,
  85000,
  90000,
  120000,
  'You shape how cities and neighborhoods develop. You analyze land use, design transportation systems, and work with communities and developers on projects. You balance competing interests—affordability, environmental impact, growth, and quality of life. Your work happens in meetings, on GIS software, and walking neighborhoods.',
  'AI can process massive datasets and generate design alternatives, but urban planning requires understanding human behavior, community values, political feasibility, and long-term consequences. Strategic judgment about what makes communities livable remains fundamentally human.',
  '[{"skill": "GIS, Data Analysis & Planning Software", "priority": "high", "how_to_develop": "Learn ArcGIS, QGIS, and urban design software. Take courses in urban data analysis and spatial visualization."}, {"skill": "Urban Design & Policy Knowledge", "priority": "high", "how_to_develop": "Study zoning codes, comprehensive planning processes, and urban design principles. Understand sustainability and housing policy."}, {"skill": "Stakeholder Engagement & Communication", "priority": "high", "how_to_develop": "Facilitate community meetings, present to city councils, and learn to explain complex plans simply. Develop negotiation skills."}]',
  '{"type": "degree", "details": "Earn a Master''s degree in Urban Planning or City Planning from an ACSP-accredited program (2 years post-bachelor''s). Some programs offer combined degrees with architecture or engineering.", "duration": "2 years post-bachelor''s"}',
  '[{"name": "Jane Jacobs", "role": "Urban Theorist & Activist", "achievement": "Challenged top-down urban planning and proved that livable cities emerge from human-centered design and organic neighborhood development."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Management Consultant',
  'management-consultant',
  'Strategist',
  NULL,
  58,
  40,
  70,
  65,
  70,
  30,
  70000,
  90000,
  110000,
  160000,
  180000,
  250000,
  'You analyze business problems and recommend solutions to help companies work better. You dive into companies'' operations, interview staff, analyze data, and figure out what''s broken. Then you present recommendations—cutting costs, reorganizing teams, changing strategies. You''re part analyst, part strategist, part salesperson.',
  'AI can analyze operational data and identify inefficiencies faster than consultants, potentially reducing demand for analytical consulting work. However, change management, strategic thinking, and client relationships remain valuable.',
  '[{"skill": "Business Analysis & Data Interpretation", "priority": "high", "how_to_develop": "Learn data analysis tools (Excel, Tableau, Python). Study business cases and develop financial modeling skills."}, {"skill": "Strategic Thinking & Problem-Solving", "priority": "high", "how_to_develop": "Take strategy courses, work on real business cases, and develop frameworks for analyzing complex problems."}, {"skill": "Client Communication & Presentation", "priority": "high", "how_to_develop": "Practice presenting to senior executives. Learn to translate analysis into clear, actionable recommendations."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in Business, Economics, or a technical field. Many consultants get MBAs from top programs. Technical consultants may have engineering or computer science degrees.", "duration": "4 years + optional MBA"}',
  '[{"name": "Peter Drucker", "role": "Management Consultant & Theorist", "achievement": "Pioneered modern management consulting and organizational thinking, influencing how companies approach strategy and operations globally."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Military Officer',
  'military-officer',
  'Strategist',
  'Guardian',
  81,
  85,
  85,
  65,
  80,
  95,
  38000,
  45000,
  60000,
  85000,
  95000,
  160000,
  'You lead military personnel and plan operations. This might mean commanding troops in the field, managing logistics, planning strategy, or overseeing specialized missions. You make high-stakes decisions, manage resources, and lead teams. The work is regimented but deeply meaningful.',
  'AI is revolutionizing military planning and tactical analysis, but military operations require human leadership, ethical judgment, situational awareness, and the ability to adapt to unpredictable situations. Human command remains essential.',
  '[{"skill": "Leadership & Team Management", "priority": "high", "how_to_develop": "Develop through officer training programs. Lead teams, learn to motivate personnel, and handle high-pressure situations."}, {"skill": "Tactical & Strategic Planning", "priority": "high", "how_to_develop": "Study military history, strategy, and operational planning. Learn through war colleges and joint military education."}, {"skill": "Technology & Equipment Expertise", "priority": "medium", "how_to_develop": "Gain expertise in your branch''s technology and systems. Understand capabilities and limitations of military equipment."}]',
  '{"type": "degree", "details": "Complete a bachelor''s degree and attend Officer Candidate School (OCS) or graduate from a military academy. Specialize based on branch (Army, Navy, Air Force, Marines, Coast Guard).", "duration": "4 years + officer training"}',
  '[{"name": "Dwight D. Eisenhower", "role": "Military Officer & President", "achievement": "Demonstrated exceptional strategic planning and leadership during WWII, proving the value of military expertise in complex operations."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Supply Chain Director',
  'supply-chain-director',
  'Strategist',
  'Operator',
  62,
  45,
  75,
  60,
  70,
  65,
  55000,
  70000,
  85000,
  115000,
  130000,
  180000,
  'You manage the flow of materials and products for a company. You work with suppliers, manage inventory, coordinate logistics, and optimize costs. You''re responsible for making sure the right products get to the right place at the right time. You spend time analyzing data, managing relationships, and solving problems.',
  'AI is rapidly automating supply chain optimization and demand forecasting, which could reduce the need for some planning roles. However, supplier relationships, strategic vendor management, and handling disruptions require human judgment.',
  '[{"skill": "Supply Chain Optimization & Analytics", "priority": "high", "how_to_develop": "Learn ERP systems, demand planning software, and optimization tools. Study operations research and supply chain management."}, {"skill": "Vendor & Relationship Management", "priority": "high", "how_to_develop": "Build strong supplier relationships, negotiate contracts, and manage vendor performance. Develop negotiation and influence skills."}, {"skill": "Process Improvement & Lean Management", "priority": "medium", "how_to_develop": "Learn Lean and Six Sigma methodologies. Lead continuous improvement initiatives and measure process efficiency."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in Supply Chain Management, Operations, or Business. Many pursue an MBA or APICS CSCP certification for advancement.", "duration": "4 years + optional certifications"}',
  '[{"name": "Wendy Mackenzie", "role": "Supply Chain Executive", "achievement": "Led supply chain transformation at major retailers, proving how effective supply chain management drives competitive advantage and profitability."}]',
  'active',
  NOW(),
  NOW()
),

-- CREATOR ARCHETYPE
(
  'Film Director',
  'film-director',
  'Creator',
  'Connector',
  78,
  75,
  85,
  95,
  85,
  30,
  35000,
  60000,
  75000,
  150000,
  200000,
  500000,
  'You bring stories to life through film. You work with writers, cinematographers, actors, and production teams to create movies or shows. You make creative decisions about every aspect—visuals, performances, pacing, tone. Some days you''re on set directing actors, other days you''re in edit suites shaping the final product.',
  'AI can generate visual effects and assist with editing, but the creative vision—understanding human emotion, storytelling, and how to move audiences—remains distinctly human. AI is a tool that enhances rather than replaces directorial creativity.',
  '[{"skill": "Visual Storytelling & Cinematography", "priority": "high", "how_to_develop": "Study film history and theory. Direct short films, learn camera work, and develop an eye for visual composition."}, {"skill": "Actor Direction & Performance", "priority": "high", "how_to_develop": "Work with actors in productions, study acting techniques, and learn how to inspire performances. Direct theater or student films."}, {"skill": "Technical Production Skills", "priority": "medium", "how_to_develop": "Learn editing software (Premiere Pro, Final Cut), understand sound design, and learn about camera equipment and lighting."}]',
  '{"type": "degree", "details": "Earn a degree in Film, Media Studies, or Fine Arts from a program with strong production focus. Build a portfolio through short films. Many successful directors start as PAs or editors.", "duration": "4 years + portfolio building"}',
  '[{"name": "Steven Spielberg", "role": "Film Director", "achievement": "Pioneered blockbuster filmmaking and proved that directorial vision could move audiences emotionally while creating technological innovations in cinema."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Game Designer',
  'game-designer',
  'Creator',
  NULL,
  65,
  30,
  75,
  90,
  60,
  25,
  50000,
  68000,
  75000,
  110000,
  120000,
  180000,
  'You create the gameplay, rules, and experience of video games. You design levels, balance mechanics, create narratives, and figure out what''s fun. You work with programmers, artists, and producers to bring your vision to life. You playtest constantly and iterate based on feedback.',
  'AI can generate content and assist with game development, but game design is fundamentally about understanding human fun and creating meaningful experiences. Creative design, level design, and narrative remain distinctly human skills.',
  '[{"skill": "Game Design Mechanics & Balance", "priority": "high", "how_to_develop": "Design tabletop games and mods for existing games. Study game theory and learn how to balance mechanics for engaging gameplay."}, {"skill": "Prototyping & Playtesting", "priority": "high", "how_to_develop": "Create prototypes using game engines like Unity or Unreal. Playtest extensively and iterate based on user feedback."}, {"skill": "Narrative & World Building", "priority": "medium", "how_to_develop": "Write stories and create game worlds. Study narrative structure and learn how to integrate story with gameplay."}]',
  '{"type": "degree", "details": "Earn a degree in Game Design or Game Development from a specialized program. Build a portfolio of game projects. Many designers start in QA or as level designers.", "duration": "4 years + portfolio"}',
  '[{"name": "Shigeru Miyamoto", "role": "Video Game Designer", "achievement": "Created iconic franchises like Super Mario and The Legend of Zelda, proving that game design is an art form requiring deep creative and mechanical understanding."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Culinary Chef',
  'culinary-chef',
  'Creator',
  'Builder',
  80,
  100,
  80,
  90,
  75,
  60,
  32000,
  45000,
  55000,
  80000,
  85000,
  150000,
  'You create dishes and menus that delight people. You manage a kitchen, source ingredients, develop recipes, and lead a team of cooks. You''re part artist, part scientist, part business manager. Every dish is a creative expression, and every service is a performance.',
  'AI can suggest recipes and optimize kitchen operations, but cooking is fundamentally about creativity, technique, and creating emotional experiences. Chef expertise in flavor profiles, technique, and understanding food culture is irreducibly human.',
  '[{"skill": "Culinary Technique & Food Science", "priority": "high", "how_to_develop": "Attend culinary school and apprentice in professional kitchens. Master knife skills, cooking methods, and food chemistry."}, {"skill": "Menu Development & Creativity", "priority": "high", "how_to_develop": "Experiment with recipes, taste widely, and understand flavor combinations. Travel and experience different cuisines."}, {"skill": "Kitchen Management & Leadership", "priority": "medium", "how_to_develop": "Work up from line cook to executive chef. Learn food safety, cost control, and team leadership."}]',
  '{"type": "trade", "details": "Complete a culinary arts program at a culinary institute (2 years) or apprentice in a professional kitchen while attending culinary school.", "duration": "2-3 years"}',
  '[{"name": "Julia Child", "role": "Chef & Culinary Educator", "achievement": "Transformed American cooking by teaching that anyone could master French cuisine, bringing joy and accessibility to the culinary arts."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Music Producer',
  'music-producer',
  'Creator',
  NULL,
  60,
  30,
  75,
  85,
  75,
  20,
  30000,
  50000,
  60000,
  100000,
  120000,
  250000,
  'You shape the sound of music. You work with artists to develop songs, arrange instrumentation, record, and mix tracks. You listen to countless demos, make creative decisions about arrangement and sound, and help artists find their voice. You''re part talent scout, part creative director, part engineer.',
  'AI can generate beats and assist with mixing, but music production is fundamentally about understanding emotion, taste, and helping artists achieve their vision. The human ear and creative judgment remain essential.',
  '[{"skill": "Music Theory & Arrangement", "priority": "high", "how_to_develop": "Study music theory, composition, and orchestration. Arrange and produce music in multiple genres."}, {"skill": "Recording & Production Technology", "priority": "high", "how_to_develop": "Learn DAWs (Ableton, Pro Tools, Logic), understand recording techniques, and develop mixing and mastering skills."}, {"skill": "Artist Development & A&R", "priority": "medium", "how_to_develop": "Work with developing artists, understand music marketing, and learn how to identify talent and develop careers."}]',
  '{"type": "self_taught", "details": "Many producers are self-taught through experimentation with recording software and working with artists. Some earn degrees in music production or recording arts.", "duration": "Variable - 3-5 years to proficiency"}',
  '[{"name": "Quincy Jones", "role": "Music Producer & Entrepreneur", "achievement": "Produced some of the best-selling albums ever, proving that production is an art requiring deep musical knowledge, technical skill, and artist understanding."}]',
  'active',
  NOW(),
  NOW()
),

-- CONNECTOR ARCHETYPE
(
  'High School Teacher',
  'high-school-teacher',
  'Connector',
  'Healer',
  76,
  95,
  90,
  80,
  90,
  80,
  35000,
  48000,
  52000,
  68000,
  70000,
  95000,
  'You teach teenagers and shape how they think about the world. You prepare lessons, lead discussions, grade assignments, and mentor students. You''re part educator, part counselor, part role model. You handle classroom management, inspire interest in your subject, and help students discover their potential.',
  'AI can deliver information and personalized practice problems, but teaching is fundamentally about human connection, inspiration, and shaping character. Teachers provide mentorship, role modeling, and the ability to adapt to each student''s needs.',
  '[{"skill": "Subject Matter Expertise", "priority": "high", "how_to_develop": "Master your subject through a bachelor''s degree. Stay current with your field and understand how it''s evolving."}, {"skill": "Teaching & Pedagogy", "priority": "high", "how_to_develop": "Complete a teaching credential program. Practice different instructional methods and learn to differentiate for diverse learners."}, {"skill": "Classroom Management & Student Connection", "priority": "high", "how_to_develop": "Learn behavior management strategies, build relationships with students, and create an inclusive classroom environment."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in your subject. Complete a teaching credential program or pursue a Master''s in Education with teacher preparation.", "duration": "4-5 years"}',
  '[{"name": "Jaime Escalante", "role": "High School Mathematics Teacher", "achievement": "Inspired disadvantaged students to excel in advanced mathematics, proving that great teachers can transform lives and overcome systemic barriers."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Sales Director',
  'sales-director',
  'Connector',
  'Strategist',
  70,
  70,
  85,
  65,
  90,
  40,
  50000,
  70000,
  90000,
  140000,
  150000,
  250000,
  'You lead a sales team and drive revenue growth. You set targets, mentor sales reps, develop strategy, and close major deals. You spend time coaching your team, analyzing sales data, and building relationships with key customers. It''s a mix of people management, strategy, and relationship building.',
  'AI can provide leads and sales intelligence, but closing deals requires human connection, empathy, and relationship building. Sales leadership increasingly relies on AI-powered tools but requires human judgment and interpersonal skill.',
  '[{"skill": "Sales Technique & Negotiation", "priority": "high", "how_to_develop": "Start in sales roles and learn customer psychology. Master negotiation, objection handling, and deal closing."}, {"skill": "Team Leadership & Coaching", "priority": "high", "how_to_develop": "Lead sales teams, mentor reps, and learn to motivate people to achieve targets. Develop emotional intelligence."}, {"skill": "Sales Analytics & Strategy", "priority": "medium", "how_to_develop": "Learn CRM systems, understand sales metrics, and develop go-to-market strategies. Study competitive markets."}]',
  '{"type": "degree", "details": "Many sales leaders earn bachelor''s degrees in business, marketing, or related fields. Success often comes from starting in sales roles and advancing through performance.", "duration": "4 years + sales experience"}',
  '[{"name": "Salesforce Executives", "role": "Sales Leadership", "achievement": "Built Salesforce from startup to the largest enterprise CRM, proving that great sales leadership drives innovation and growth."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Community Organizer',
  'community-organizer',
  'Connector',
  'Guardian',
  74,
  85,
  90,
  80,
  95,
  50,
  30000,
  42000,
  48000,
  65000,
  70000,
  95000,
  'You mobilize people to tackle community issues. You listen to what community members care about, build coalitions, develop campaigns, and push for change. You might organize around housing, education, environmental issues, or workers'' rights. You spend time in communities, at meetings, and building relationships.',
  'AI can help with data and messaging, but organizing fundamentally depends on human relationships, trust, and the ability to inspire collective action. The human connection and grassroots mobilization are irreplaceable.',
  '[{"skill": "Community Relationship Building", "priority": "high", "how_to_develop": "Work in communities, listen deeply, and build trust. Learn how to identify leaders and support them."}, {"skill": "Campaign Strategy & Tactics", "priority": "high", "how_to_develop": "Study successful campaigns, learn pressure tactics, and understand how to win concrete gains. Work on real campaigns."}, {"skill": "Public Speaking & Facilitation", "priority": "medium", "how_to_develop": "Speak at community meetings, facilitate large groups, and learn to inspire action. Practice public speaking."}]',
  '{"type": "self_taught", "details": "Many community organizers learn through direct experience in organizations. Some earn degrees in social work, public policy, or community development. Mentorship is key.", "duration": "Variable - typically learn through 2-3 year immersion"}',
  '[{"name": "Ella Baker", "role": "Community Organizer & Civil Rights Leader", "achievement": "Demonstrated that grassroots organizing and empowering community members is more powerful than top-down leadership for creating lasting social change."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Executive Recruiter',
  'executive-recruiter',
  'Connector',
  NULL,
  52,
  60,
  75,
  55,
  85,
  25,
  50000,
  70000,
  90000,
  150000,
  160000,
  300000,
  'You match top talent with senior leadership positions. You build relationships with executives, understand their strengths and motivations, and connect them to companies seeking leadership. You spend time making calls, having conversations, and building trust with people who can shape careers.',
  'AI can screen candidates and identify prospects, but executive recruiting depends entirely on personal relationships, trust, and the ability to assess executive fit. These human skills are central to the role.',
  '[{"skill": "Relationship Building & Influence", "priority": "high", "how_to_develop": "Build relationships in your industry, stay connected to executives, and develop influence. Network extensively."}, {"skill": "Talent Assessment", "priority": "high", "how_to_develop": "Learn to assess executive capabilities, understand organizational culture, and predict success. Work with executives over time."}, {"skill": "Negotiation & Deal Making", "priority": "medium", "how_to_develop": "Learn to negotiate between candidates and companies. Manage complex placement deals and understand compensation structures."}]',
  '{"type": "self_taught", "details": "Many executive recruiters come from sales, HR, or executive backgrounds. Learn through mentorship and experience building relationships in corporate environments.", "duration": "Variable - typically 3-5 years to expertise"}',
  '[{"name": "Korn Ferry", "role": "Executive Search Firm", "achievement": "Built a global executive search business by proving that access to trusted relationships and industry expertise is invaluable for placing top leaders."}]',
  'active',
  NOW(),
  NOW()
),

-- GUARDIAN ARCHETYPE
(
  'Cybersecurity Analyst',
  'cybersecurity-analyst',
  'Guardian',
  NULL,
  71,
  40,
  85,
  70,
  55,
  75,
  60000,
  78000,
  90000,
  125000,
  140000,
  190000,
  'You protect companies from cyber attacks. You monitor systems for threats, analyze security incidents, implement safeguards, and stay ahead of hackers. You work with firewalls, encryption, threat intelligence, and complex networks. It''s like being a digital security guard—always watching, always learning about new threats.',
  'AI is becoming essential for threat detection and response, but cybersecurity requires human judgment to distinguish real threats from false positives, understand attacker behavior, and make strategic decisions. Analysts increasingly partner with AI tools.',
  '[{"skill": "Network Security & Systems Administration", "priority": "high", "how_to_develop": "Build expertise in network architecture, firewalls, and IT systems. Get CompTIA Security+ or CEH certifications."}, {"skill": "Threat Analysis & Incident Response", "priority": "high", "how_to_develop": "Study threat intelligence, learn to analyze malware, and practice incident response. Complete GCIH or similar certifications."}, {"skill": "Compliance & Risk Management", "priority": "medium", "how_to_develop": "Understand security regulations (GDPR, HIPAA, PCI-DSS) and learn how to assess and manage security risks."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in Cybersecurity, Computer Science, or Information Technology. Get industry certifications like Security+, CEH, or CISSP. Many roles require 2-3 years IT experience first.", "duration": "4 years + certifications"}',
  '[{"name": "Kevin Mitnick", "role": "Cybersecurity Expert", "achievement": "Transformed from famous hacker to security consultant, proving that understanding attacker mentality is critical for defending systems."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Environmental Scientist',
  'environmental-scientist',
  'Guardian',
  'Explorer',
  69,
  75,
  80,
  75,
  60,
  75,
  40000,
  55000,
  60000,
  85000,
  90000,
  130000,
  'You study and protect the environment. You conduct field research, analyze pollution and climate data, assess environmental impacts of development, and recommend solutions. You might work for government agencies, nonprofits, or private companies. You combine fieldwork with lab work and data analysis.',
  'AI can process environmental data at scale and model climate scenarios, but environmental science requires field expertise, complex systems thinking, and the ability to navigate policy tradeoffs. Expertise remains essential.',
  '[{"skill": "Environmental Testing & Field Methods", "priority": "high", "how_to_develop": "Learn field sampling techniques, lab analysis, and environmental monitoring. Get hands-on experience in the field."}, {"skill": "Data Analysis & Modeling", "priority": "high", "how_to_develop": "Master statistics, GIS, and environmental modeling software. Learn to interpret complex environmental data."}, {"skill": "Regulatory & Policy Knowledge", "priority": "medium", "how_to_develop": "Understand environmental regulations (Clean Air Act, Clean Water Act, etc.). Learn how science informs policy decisions."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in Environmental Science, Ecology, or Environmental Engineering. Many positions require a Master''s degree for research or specialized roles.", "duration": "4 years + optional Master''s"}',
  '[{"name": "Rachel Carson", "role": "Environmental Scientist & Writer", "achievement": "Used scientific research to expose the dangers of pesticides, launching the modern environmental movement and proving science''s power to protect nature."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Police Detective',
  'police-detective',
  'Guardian',
  'Explorer',
  77,
  85,
  90,
  75,
  80,
  90,
  42000,
  58000,
  62000,
  85000,
  90000,
  125000,
  'You investigate crimes and catch criminals. You analyze evidence, interview witnesses and suspects, build cases, and work with prosecutors. You combine detective work with strong communication skills and understanding of human psychology. The work is intellectually challenging and personally demanding.',
  'AI can analyze crime patterns and assist with forensics, but detective work fundamentally requires human judgment, interpersonal skills, and the ability to understand human motivation. Core investigative work remains human-dependent.',
  '[{"skill": "Investigation & Evidence Analysis", "priority": "high", "how_to_develop": "Start in patrol, learn investigative techniques, and study forensics and evidence handling. Work on cases with experienced detectives."}, {"skill": "Interview & Interrogation", "priority": "high", "how_to_develop": "Learn interview techniques, study human psychology, and practice building rapport with witnesses and suspects."}, {"skill": "Legal Knowledge & Case Building", "priority": "high", "how_to_develop": "Understand criminal law, evidence rules, and how to build prosecutable cases. Work closely with attorneys."}]',
  '{"type": "degree", "details": "Earn a high school diploma or GED. Most departments require 2-4 years patrol experience before becoming a detective. Some positions require college coursework or an associate''s degree.", "duration": "4 years + police training"}',
  '[{"name": "Cold Case Detectives", "role": "Investigation Specialists", "achievement": "Using persistence, modern technology, and investigative skill, solve decades-old cases and bring closure to families, proving the value of dedicated detective work."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Compliance Officer',
  'compliance-officer',
  'Guardian',
  NULL,
  48,
  30,
  70,
  50,
  60,
  80,
  50000,
  65000,
  75000,
  100000,
  110000,
  160000,
  'You ensure companies follow laws and regulations. You develop compliance policies, train employees, audit operations, and respond to regulatory requirements. You work with lawyers, auditors, and senior management. It''s detail-oriented work focused on reducing risk and preventing violations.',
  'AI can identify compliance risks and automate monitoring, potentially reducing need for some compliance roles. However, judgment about regulatory strategy and responding to novel situations requires human expertise.',
  '[{"skill": "Regulatory Knowledge & Legal Understanding", "priority": "high", "how_to_develop": "Study regulations relevant to your industry. Work with legal teams and stay current on compliance requirements."}, {"skill": "Risk Assessment & Audit", "priority": "high", "how_to_develop": "Learn audit procedures, risk assessment frameworks, and how to identify compliance gaps. Get certifications like CIA or CISA."}, {"skill": "Documentation & Process Development", "priority": "medium", "how_to_develop": "Develop policies and procedures. Learn to document compliance and create audit trails."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in Business, Law, Accounting, or related field. Many roles require professional certifications like CIA, CISM, or industry-specific compliance certifications.", "duration": "4 years + certifications"}',
  '[{"name": "SOX Compliance Professionals", "role": "Compliance Leaders", "achievement": "Helped companies navigate Sarbanes-Oxley and other regulations, proving that strong compliance prevents scandals and protects shareholders."}]',
  'active',
  NOW(),
  NOW()
),

-- EXPLORER ARCHETYPE
(
  'Marine Biologist',
  'marine-biologist',
  'Explorer',
  'Guardian',
  75,
  80,
  80,
  85,
  60,
  80,
  35000,
  50000,
  55000,
  80000,
  85000,
  130000,
  'You study marine ecosystems and ocean life. You conduct fieldwork on boats or underwater, collect specimens, analyze data, and work to understand and protect ocean environments. Some days you''re diving collecting data, other days you''re in labs analyzing specimens or writing research papers.',
  'AI can help analyze marine data and model ocean systems, but marine biology requires field expertise, hands-on observation skills, and the ability to understand complex ecosystems. Core research skills remain irreducibly human.',
  '[{"skill": "Field Research & Diving", "priority": "high", "how_to_develop": "Get SCUBA certification, learn fieldwork techniques, and spend time on research vessels. Develop hands-on observation skills."}, {"skill": "Data Analysis & Research Methods", "priority": "high", "how_to_develop": "Master statistics, GIS, and data analysis. Learn experimental design and proper research methodology."}, {"skill": "Species Identification & Taxonomy", "priority": "medium", "how_to_develop": "Study marine taxonomy, learn to identify species, and develop expertise in your research area."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in Marine Biology or Biology with marine focus. Most research positions require a Master''s or PhD degree.", "duration": "4 years + graduate degree"}',
  '[{"name": "Sylvia Earle", "role": "Marine Biologist & Ocean Explorer", "achievement": "Pioneered deep-sea exploration and ocean conservation, proving that hands-on marine research drives critical understanding of ocean ecosystems."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Investigative Journalist',
  'investigative-journalist',
  'Explorer',
  'Guardian',
  68,
  70,
  85,
  85,
  75,
  55,
  35000,
  50000,
  55000,
  80000,
  85000,
  130000,
  'You uncover hidden stories and expose wrongdoing. You interview sources, research documents, analyze data, and write compelling stories that matter. You investigate corruption, abuse, environmental destruction, or other important issues. It requires tenacity, skepticism, and strong writing.',
  'AI can help analyze large datasets and find patterns, but investigative journalism depends on human relationships, trust-building with sources, and the judgment to distinguish truth from misinformation. Core investigation remains human-driven.',
  '[{"skill": "Interviewing & Source Development", "priority": "high", "how_to_develop": "Practice interviewing, develop sources in your beat, and learn to build trust with sources. Work on real stories."}, {"skill": "Research & Data Analysis", "priority": "high", "how_to_develop": "Learn data journalism, FOIA requests, document analysis, and database investigation. Master spreadsheets and analysis tools."}, {"skill": "Writing & Storytelling", "priority": "high", "how_to_develop": "Write constantly, study great journalism, and develop a clear, compelling writing style. Get feedback from editors."}]',
  '{"type": "degree", "details": "Earn a degree in Journalism, English, or related field. Many reporters start at smaller outlets and build experience. Strong portfolios matter more than specific degrees.", "duration": "4 years + newsroom experience"}',
  '[{"name": "Bob Woodward & Carl Bernstein", "role": "Investigative Journalists", "achievement": "Uncovered Watergate scandal through persistent investigation and source development, proving journalism''s power to hold power accountable."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Aerospace Engineer',
  'aerospace-engineer',
  'Explorer',
  'Builder',
  79,
  70,
  85,
  85,
  65,
  90,
  60000,
  75000,
  85000,
  115000,
  125000,
  175000,
  'You design and improve aircraft and spacecraft. You work with teams on aerodynamics, structures, propulsion, and systems. You use simulation and testing to solve problems and push the boundaries of what''s possible. You might work for aerospace companies, space agencies, or airlines.',
  'AI is revolutionizing design optimization and simulations, allowing engineers to test thousands of designs. However, aerospace engineering requires deep physics understanding, judgment about safety, and innovation that combines with rather than replaces engineering expertise.',
  '[{"skill": "Aerodynamics & Fluid Mechanics", "priority": "high", "how_to_develop": "Master thermodynamics, fluid mechanics, and aeronautical principles through engineering degree. Use CFD (Computational Fluid Dynamics) software."}, {"skill": "CAD & Simulation Software", "priority": "high", "how_to_develop": "Learn CATIA, ANSYS, MATLAB, and other aerospace design tools. Practice complex simulations and design optimization."}, {"skill": "Systems Thinking & Safety", "priority": "high", "how_to_develop": "Understand how aircraft systems integrate. Study failure analysis and learn to design for safety and reliability."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in Aerospace Engineering (ABET accredited). Pursue Professional Engineer (PE) licensing. Many advanced roles require a Master''s degree.", "duration": "4 years + optional Master''s"}',
  '[{"name": "Elon Musk & SpaceX Engineers", "role": "Aerospace Engineers", "achievement": "Revolutionized space exploration by designing reusable rockets, proving that engineering innovation can dramatically reduce costs and expand access to space."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Archaeological Researcher',
  'archaeological-researcher',
  'Explorer',
  NULL,
  73,
  85,
  85,
  85,
  65,
  75,
  32000,
  48000,
  55000,
  75000,
  80000,
  120000,
  'You study human history by excavating and analyzing artifacts. You conduct fieldwork at dig sites, catalog findings, analyze materials, and piece together stories of past civilizations. You combine detective work with scientific analysis. Some seasons you''re excavating, other times you''re in labs studying artifacts.',
  'AI can assist with artifact classification and pattern analysis, but archaeology fundamentally depends on field expertise, careful excavation technique, and the contextual judgment required to interpret findings. Hands-on skill remains central.',
  '[{"skill": "Excavation & Field Methods", "priority": "high", "how_to_develop": "Participate in archaeological digs and learn proper excavation techniques. Understand stratigraphy and site documentation."}, {"skill": "Material Analysis & Dating", "priority": "high", "how_to_develop": "Learn radiocarbon dating, ceramic analysis, and artifact classification. Study in labs and gain hands-on experience."}, {"skill": "Research & Analysis", "priority": "medium", "how_to_develop": "Learn to interpret artifacts within cultural contexts. Study archaeological theory and develop research questions."}]',
  '{"type": "degree", "details": "Earn a Bachelor''s degree in Archaeology or related field. Most research positions require a Master''s degree in Archaeology. PhD required for university positions.", "duration": "4 years + graduate degree"}',
  '[{"name": "Dr. Sarah Parcak", "role": "Archaeologist & Satellite Imaging Expert", "achievement": "Used technology combined with traditional archaeology to discover thousands of previously unknown archaeological sites, proving innovation enhances archaeological discovery."}]',
  'active',
  NOW(),
  NOW()
),

-- OPERATOR ARCHETYPE
(
  'Air Traffic Controller',
  'air-traffic-controller',
  'Operator',
  'Guardian',
  86,
  60,
  95,
  70,
  75,
  95,
  52000,
  68000,
  85000,
  120000,
  130000,
  180000,
  'You manage air traffic and keep planes safe. You guide pilots during takeoff, landing, and flight using radar and communication systems. You make split-second decisions managing dozens of aircraft simultaneously. The work requires intense focus, quick thinking, and unwavering attention to safety.',
  'AI can assist with traffic optimization and provide alerting systems, but air traffic control fundamentally requires human judgment, quick decision-making under uncertainty, and the accountability that humans provide. Automation remains an assistant, not a replacement.',
  '[{"skill": "Air Traffic Control Systems", "priority": "high", "how_to_develop": "Complete FAA ATC training program. Learn radar systems, communication protocols, and airport operations."}, {"skill": "Decision-Making Under Pressure", "priority": "high", "how_to_develop": "Develop through intense training and simulations. Practice managing multiple conflicting demands with perfect safety."}, {"skill": "Communication & Coordination", "priority": "high", "how_to_develop": "Master radio communication, coordination procedures, and working with pilots and other controllers."}]',
  '{"type": "apprenticeship", "details": "Complete the FAA Academy training program (7-10 weeks). Then undergo on-the-job training at an air traffic facility (2-3 years) before certification.", "duration": "3-4 years total"}',
  '[{"name": "Chesley Sullenberger", "role": "Airline Captain & Former Air Traffic Controller", "achievement": "Used air traffic control knowledge and exceptional judgment to safely land plane on Hudson River, saving all 155 people aboard."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Construction Project Manager',
  'construction-project-manager',
  'Operator',
  'Builder',
  78,
  85,
  85,
  70,
  80,
  80,
  50000,
  65000,
  75000,
  105000,
  115000,
  160000,
  'You oversee construction projects from start to finish. You manage budgets, schedules, teams, and quality. You work with architects, contractors, and clients. You spend time at job sites, in meetings, and solving unexpected problems. Safety and quality are paramount.',
  'AI can optimize scheduling and budgets, but construction management requires on-site presence, quick decision-making about problems, team leadership, and stakeholder management. Human judgment about safety and quality remains essential.',
  '[{"skill": "Project Management & Scheduling", "priority": "high", "how_to_develop": "Learn project management software (Microsoft Project, Procore). Get PMP or construction-specific certifications."}, {"skill": "Construction Knowledge & Safety", "priority": "high", "how_to_develop": "Build deep knowledge of construction methods, materials, and codes. Complete OSHA training and develop safety expertise."}, {"skill": "Leadership & Problem-Solving", "priority": "high", "how_to_develop": "Lead teams through complex projects. Learn to solve problems creatively and keep projects on track."}]',
  '{"type": "degree", "details": "Earn a degree in Construction Management, Civil Engineering, or related field. Many project managers start as construction workers or supervisors and advance through experience.", "duration": "4 years + experience"}',
  '[{"name": "Great Project Managers", "role": "Construction Leadership", "achievement": "Manage complex projects like skyscrapers and infrastructure, proving that exceptional management and problem-solving deliver projects on time and on budget."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Logistics Coordinator',
  'logistics-coordinator',
  'Operator',
  NULL,
  55,
  70,
  65,
  50,
  65,
  60,
  32000,
  45000,
  50000,
  70000,
  75000,
  110000,
  'You coordinate the movement of goods and manage inventory. You track shipments, schedule pickups and deliveries, manage warehouse operations, and solve logistics problems. You use software to track everything and communicate with drivers, warehouses, and customers.',
  'AI is rapidly automating route optimization and warehouse management, which could reduce coordination roles. However, problem-solving, vendor relationships, and responding to disruptions require human judgment.',
  '[{"skill": "Logistics Software & Systems", "priority": "high", "how_to_develop": "Learn TMS (Transportation Management Systems) and WMS (Warehouse Management Systems). Study supply chain software."}, {"skill": "Problem-Solving & Troubleshooting", "priority": "high", "how_to_develop": "Work through real logistics problems—shipment delays, inventory discrepancies, routing issues. Develop quick thinking skills."}, {"skill": "Communication & Coordination", "priority": "medium", "how_to_develop": "Practice coordinating with multiple parties. Learn to communicate clearly about complex logistics situations."}]',
  '{"type": "degree", "details": "Earn a certificate or degree in Logistics or Supply Chain. Many coordinators start in entry-level warehouse or transportation roles and advance.", "duration": "2-4 years"}',
  '[{"name": "UPS & FedEx Operations", "role": "Logistics Leadership", "achievement": "Built world-class logistics networks that deliver millions of packages daily, proving that logistics coordination is essential infrastructure."}]',
  'active',
  NOW(),
  NOW()
),
(
  'Restaurant General Manager',
  'restaurant-general-manager',
  'Operator',
  'Connector',
  72,
  95,
  85,
  70,
  85,
  65,
  40000,
  55000,
  60000,
  85000,
  90000,
  140000,
  'You run a restaurant. You manage staff, oversee operations, maintain quality and safety, manage budgets, and ensure customers have great experiences. You handle everything from hiring cooks to resolving customer complaints. You''re part manager, part chef, part psychologist.',
  'AI can help with scheduling and inventory management, but restaurant management fundamentally depends on real-time decisions, staff leadership, customer relationship building, and the judgment to balance competing priorities. Human leadership remains central.',
  '[{"skill": "Restaurant Operations & Management", "priority": "high", "how_to_develop": "Work up from entry-level restaurant positions. Learn P&L management, food safety, and operations from experienced managers."}, {"skill": "Staff Leadership & Training", "priority": "high", "how_to_develop": "Lead restaurant teams, develop cultures, and train staff. Learn to motivate people in fast-paced environments."}, {"skill": "Customer Service & Problem Resolution", "priority": "high", "how_to_develop": "Handle customer issues with grace. Learn to turn complaints into loyalty and create great customer experiences."}]',
  '{"type": "apprenticeship", "details": "Most restaurant GMs work their way up from entry-level positions. Some earn degrees in Hospitality or Business. On-the-job training and mentorship are key.", "duration": "5-7 years to GM role"}',
  '[{"name": "Danny Meyer", "role": "Restaurant Leader & Hospitality Innovator", "achievement": "Built world-class restaurant groups by proving that exceptional operations, staff culture, and customer relationships drive restaurant success."}]',
  'active',
  NOW(),
  NOW()
);
